db:
  url: http://seliger.db.kovardin.ru:8080
  token: "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MzczMTA4MzIsImlkIjoiODEyMjA0MDYtNDg1NC00ZDRiLTgxN2UtNjFmNGEwOTJjZGM0IiwibmJmIjoxNDQ0NDc4NDAwLCJwIjp7InJ3Ijp7Im5zIjpbInNlbGlnZXIiXX19fQ.Ow5LzKgVY2a-lgK4jmeDSL1cf5ENuGdl9FZtTFdiGXjoqTY5JvHg2rO3GEK-YHF4Nk7D9B19T4Hh_Kk-xBPOCA"